### ISSUE TITLE
[Schema Inaccuracy] Issue comment creation `author_association` returns values with inconsistent case

### ISSUE THREAD

**Issue by mlbright** [github/rest-api-description#173]
# Schema Inaccuracy

At least with GitHub Enterprise 2.21, when creating an issue comment, the value of `author_association` can be `MEMBER`.

## Expected

One of `Collaborator`, `Contributor`, `FirstTimer`, `FirstTimeContributor`, `Mannequin`, `Member`, `Owner`.

## Reproduction Steps

```
curl \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Authorization: token $GITHUB_TOKEN" \
    "https://git.autodesk.com/api/v3/repos/test-org/test-repo/issues/24/comments" \
    -d '{"body":"body"}'
```

**Comment by xuorig** [comment]
@mlbright the API does return the values as uppercase, but our OpenAPI description also describes them as such. Maybe this was fixed?

**Comment by tim-finnigan** [comment]
@xuorig We've observed many inconsistencies with the "author_association" value. 

When using webhooks triggered upon issue comments, it will return "author_association":"None" or "author_association":"Contributor" when it should return "author_association":"Member". 

Can you point me in the right direction to understand this behavior if it is expected the expected behavior?
