### ISSUE TITLE
[Schema Inaccuracy] security object mixes function with state

### ISSUE THREAD

**Issue by orubel** [github/rest-api-description#18]
# Schema Inaccuracy

The request/response for the API call are at a minimum, only concerned with ROLES/Privileges associated with an endpoint... not with the OAuth handshake. That is all function handled on the backend.

{
  "type": "oauth2",
  "flows": {
    "implicit": {
      "authorizationUrl": "https://example.com/api/oauth/dialog",
      "scopes": {
        "write:pets": "modify pets in your account",
        "read:pets": "read your pets"
      }
    }
  }
}

This function can be defined (and usually is) in separate more secure documents that don't have to be syncronized and/or cached. Also this data is single use wheras the other data in the document is shared.

## Expected

Security is better handled by associating ROLES with endpoints so that once token is issued, a check can be easily made against stated ROLES associated with endpoints

ex.
		"REQUEST": {
			"permitAll":["firstName","username","lastName","email"],
                        "ROLE_ADMIN":["enabled","password","id","version"]
		},
		"RESPONSE": {
			"permitAll":["email"],
                        "ROLE_ADMIN":["id","version"]
		}

Above shows how ROLE_ADMIN would get a concatenated dataset of 'permitAll' plus their own privilege.

This keeps the schema related ONLY to the request/response call flow.

## Reproduction Steps

ex
curl -v -H "Content-Type: application/json" -H "Authorization: Bearer a7ectf7qgulb38bu22l136r7cf0qv12j"  --request GET "http://localhost:8080/v1.6.58/person/show/225"

**Comment by orubel** [comment]
whoa you just close without comment all my issue? You stated to submit issues with the spec here man

**Comment by orubel** [comment]
ok dude. I submitted it as a security issue. https://hackerone.com/bugs?report_id=944326&subject=user

**Comment by xuorig** [comment]
👋 @orubel

This description is based on the OpenAPI specification so we adhere to those standards. I closed your issue because it seems to be about the OpenAPI specification itself in which case I'd propose filing an issue here: https://github.com/OAI/OpenAPI-Specification. This seems to be the case with your other issues as well. Looks like [you've done that already in the past](https://github.com/OAI/OpenAPI-Specification/issues/1411) about this very issue.

If there is a specific problem with the OpenAPI description found in this repository, we will gladly take a look if you can describe the specific issue. I encourage you to read our [Code of Conduct](https://github.com/github/rest-api-description/blob/main/CODE_OF_CONDUCT.md) as well 🙇 .

**Comment by orubel** [comment]
But it is not a standard. It is attempting to BECOME a standard. So when large companies adopt, it is important to point out these issue AS WELL AS the security issue that I also submitted. This is one of the reasons I talked to Netflix and Amazon and had Amazon abstract their data from their Lambdas so they could at LEAST sync/share it.

It's an architectural cross cutting concern that causes a whole list of issues: https://www.slideshare.net/bobdobbes/api-pattern#15
