### ISSUE TITLE
[Schema Inaccuracy] Unused and underspecified fields in base-gist component schema

### ISSUE THREAD

**Issue by pluehne** [github/rest-api-description#214]
# Schema Inaccuracy

The `forks` and `history` fields of the `base-gist` component schema are underspecified (they are arrays of an unknown type):

```yaml
forks:
  type: array
  items: {}
history:
  type: array
  items: {}
```

In addition to that, I haven’t been able to get a single response from GitHub.com from the Gist endpoints that return `base-gist` including the `forks` or the `history` field.

My impression is that these have been included by mistake or are hidden behind a preview flag that is not available yet.

## Expected

I’d expect these fields to either have a fully specified item schema or to be absent from the `base-gist` component schema entirely.

## Reproduction Steps

1. Create a gist and make one edit to have two revisions.
2. Have someone fork the gist.
3. ```sh
   curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/gists
   ```
4. The response contains neither `forks` nor `history`.

**Comment by xuorig** [comment]
@pluehne thanks for the report, you're right, those attributes are only included in certain resources (gist revisions, update gist for example). We'll fix this.

**Comment by baywet** [comment]
@kfcampbell @nickfloyd We're using your description as a smoke test for kiota and this issue is a blocker for people unless they exclude those endpoints using Kiota's filtering capability. Prioritizing this fix in the description would not only help your exploratory work but also help our smoke tests efforts.
Ideally these properties would get removed or a schema would be provided.

**Comment by nickfloyd** [comment]
Hey @baywet I am in the middle of these changes.  They are considered breaking changes since we're removing properties. The changes will be released under our versioning framework, and once I get the changeset merged it you'll be able to use our `next` [version](https://github.com/github/rest-api-description/tree/main/descriptions-next) to get the benefits of this change to the descriptions.

**Comment by nickfloyd** [comment]
@baywet This just got merged.  Be looking for it in the version `next` descriptions.
