### ISSUE TITLE
Documentation links are now broken

### ISSUE THREAD

**Issue by baywet** [github/rest-api-description#2828]
It seems the documentation platform changed their link structure a couple of months ago.

The OpenAPI description contains
`https://docs.github.com/en/rest/pulls?apiVersion=2022-11-28#list-pull-requests`
Which used to get you down right to the API call sample, but now get's stuck on the table of content.

This is what the docs platform expects

`https://docs.github.com/en/free-pro-team@latest/rest/pulls/pulls#create-a-pull-request`

**Comment by nickfloyd** [comment]
@baywet I checked the docs like you posted from the OpenAPI description, they were changed to support OpenAPI versioning.

I see what you mean - when linking directly to an operation the link in the descriptions seem to just default to the section and not the operation. So `pulls` instead of `pulls#list-pull-requests`

We'll have a look at what's going on and get a better idea of expected behavior. Thank you for catching this.
