### ISSUE TITLE
[Schema Inaccuracy] <Describe Problem>
Joshua Paul Verdin 

### ISSUE THREAD

**Issue by verdinjoshua06** [github/rest-api-description#4320]
# Schema Inaccuracy

**Comment by MORTEZAMIRSALI** [comment]
With greetings and politeness, don't be tired, dear friend, we have been working on the issue for several days and hours, but because it has been vandalized from the depths, I personally will not destroy my address. Anyway, I don't want to talk about it, but please assign a new address with the remaining assets.  I and my partners are having a hard time in the new year, please do something

**Comment by MORTEZAMIRSALI** [comment]
I am sure that as the new year approaches, we will all go to the arms of Christ with joy. Currently, I am under a lot of pressure from my partners. I ask your team to define a new address and location, thanks
